name: SauceDemo Otomasyon HattÄ± ğŸš€

on:
  push:
    branches: [ main ] # Kodu main'e attÄ±ÄŸÄ±nda Ã§alÄ±ÅŸÄ±r
  workflow_dispatch:   # Elle tetiklemek iÃ§in

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-ve-rapor:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Ã‡ek (Checkout)
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: KÃ¼tÃ¼phaneleri YÃ¼kle
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Playwright TarayÄ±cÄ±larÄ±nÄ± Kur
        run: playwright install chromium

      - name: Testleri KoÅŸtur (SauceDemo)
        # --alluredir: SonuÃ§larÄ± 'allure-results' klasÃ¶rÃ¼ne yazar
        # continue-on-error: Test baÅŸarÄ±sÄ±z olsa bile durma, raporu Ã¼ret.
        run: pytest playwright_test/test_sauce_demo.py --trace on  --alluredir=allure-results --video=retain-on-failure
        continue-on-error: true
      
      - name: Trace DosyalarÄ±nÄ± YÃ¼kle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results

      - name: Allure Raporunu Ä°nÅŸa Et ğŸ“Š
        uses: simple-elf/allure-report-action@master
        if: always() # Testler patlasa bile bu adÄ±m Ã§alÄ±ÅŸsÄ±n
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages

      - name: Raporu GitHub Pages iÃ§in HazÄ±rla
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    needs: test-ve-rapor
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: CanlÄ±ya Al (Deploy) ğŸŒ
        id: deployment
        uses: actions/deploy-pages@v4
